# Generated by Django 3.0.5 on 2020-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=300)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
